on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    
    
    env:
      Solution_Name: ControllerRestDemo.sln
      Test_Project_Path: /ControllerRestDemoTest/ControllerRestDemoTest.csproj

    steps:
    - name: .NET build
      run: dotnet build
      
    - name: .NET test
      run: dotnet test
